// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTMWcuSkHic3HZ48PjulFIevK2FJfixy8',
    appId: '1:828612977621:web:8ede10d3fffcf402fa935c',
    messagingSenderId: '828612977621',
    projectId: 'question-paper-af72a',
    authDomain: 'question-paper-af72a.firebaseapp.com',
    storageBucket: 'question-paper-af72a.appspot.com',
    measurementId: 'G-C5VD2P2LY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM33cDWaW-n3RUNU7bO28IsasS4g--8kA',
    appId: '1:828612977621:android:e909723d761cc3b8fa935c',
    messagingSenderId: '828612977621',
    projectId: 'question-paper-af72a',
    storageBucket: 'question-paper-af72a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQVdb52KOI--d42xtac_4-XF0c_HQI8M',
    appId: '1:828612977621:ios:aadc6fad44f25da4fa935c',
    messagingSenderId: '828612977621',
    projectId: 'question-paper-af72a',
    storageBucket: 'question-paper-af72a.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQVdb52KOI--d42xtac_4-XF0c_HQI8M',
    appId: '1:828612977621:ios:aadc6fad44f25da4fa935c',
    messagingSenderId: '828612977621',
    projectId: 'question-paper-af72a',
    storageBucket: 'question-paper-af72a.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTMWcuSkHic3HZ48PjulFIevK2FJfixy8',
    appId: '1:828612977621:web:7ea1fa073b08afeafa935c',
    messagingSenderId: '828612977621',
    projectId: 'question-paper-af72a',
    authDomain: 'question-paper-af72a.firebaseapp.com',
    storageBucket: 'question-paper-af72a.appspot.com',
    measurementId: 'G-T4ZZZPE3W3',
  );
}
